version: '2'
services:
    mongo-6-2:
        container_name: "mongo-6-2"
        image: mongobuild
        ports:
            - "30020:27017"
        command: mongod --replSet rs6 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-6-3:
        container_name: "mongo-6-3"
        image: mongobuild
        ports:
            - "30021:27017"
        command: mongod --replSet rs6 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-6-1:
        container_name: "mongo-6-1"
        image: mongobuild
        ports:
            - "30019:27017"
        command: mongod --replSet rs6 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-6-2:mongo-6-2
            - mongo-6-3:mongo-6-3
        restart: always

    mongo-rs6-setup:
        container_name: "mongo-rs6-setup"
        image: mongobuild
        depends_on:
            - "mongo-6-1"
            - "mongo-6-2"
            - "mongo-6-3"
        links:
            - mongo-6-1:mongo-6-1
            - mongo-6-2:mongo-6-2
            - mongo-6-3:mongo-6-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-6-1
            - MONGO2=mongo-6-2
            - MONGO3=mongo-6-3
            - RS=rs6
        entrypoint: [ "/scripts/setup.sh" ]

        
