version: '2'
services:
    mongo-26-2:
        container_name: "mongo-26-2"
        image: mongobuild
        ports:
            - "30080:27017"
        command: mongod --replSet rs26 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-26-3:
        container_name: "mongo-26-3"
        image: mongobuild
        ports:
            - "30081:27017"
        command: mongod --replSet rs26 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-26-1:
        container_name: "mongo-26-1"
        image: mongobuild
        ports:
            - "30079:27017"
        command: mongod --replSet rs26 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-26-2:mongo-26-2
            - mongo-26-3:mongo-26-3
        restart: always

    mongo-rs26-setup:
        container_name: "mongo-rs26-setup"
        image: mongobuild
        depends_on:
            - "mongo-26-1"
            - "mongo-26-2"
            - "mongo-26-3"
        links:
            - mongo-26-1:mongo-26-1
            - mongo-26-2:mongo-26-2
            - mongo-26-3:mongo-26-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-26-1
            - MONGO2=mongo-26-2
            - MONGO3=mongo-26-3
            - RS=rs26
        entrypoint: [ "/scripts/setup.sh" ]

        
