version: '2'
services:
    mongo-43-2:
        container_name: "mongo-43-2"
        image: mongobuild
        ports:
            - "30131:27017"
        command: mongod --replSet rs43 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-43-3:
        container_name: "mongo-43-3"
        image: mongobuild
        ports:
            - "30132:27017"
        command: mongod --replSet rs43 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-43-1:
        container_name: "mongo-43-1"
        image: mongobuild
        ports:
            - "30130:27017"
        command: mongod --replSet rs43 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-43-2:mongo-43-2
            - mongo-43-3:mongo-43-3
        restart: always

    mongo-rs43-setup:
        container_name: "mongo-rs43-setup"
        image: mongobuild
        depends_on:
            - "mongo-43-1"
            - "mongo-43-2"
            - "mongo-43-3"
        links:
            - mongo-43-1:mongo-43-1
            - mongo-43-2:mongo-43-2
            - mongo-43-3:mongo-43-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-43-1
            - MONGO2=mongo-43-2
            - MONGO3=mongo-43-3
            - RS=rs43
        entrypoint: [ "/scripts/setup.sh" ]

        
