version: '2'
services:
    mongo-17-2:
        container_name: "mongo-17-2"
        image: mongobuild
        ports:
            - "30053:27017"
        command: mongod --replSet rs17 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-17-3:
        container_name: "mongo-17-3"
        image: mongobuild
        ports:
            - "30054:27017"
        command: mongod --replSet rs17 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-17-1:
        container_name: "mongo-17-1"
        image: mongobuild
        ports:
            - "30052:27017"
        command: mongod --replSet rs17 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-17-2:mongo-17-2
            - mongo-17-3:mongo-17-3
        restart: always

    mongo-rs17-setup:
        container_name: "mongo-rs17-setup"
        image: mongobuild
        depends_on:
            - "mongo-17-1"
            - "mongo-17-2"
            - "mongo-17-3"
        links:
            - mongo-17-1:mongo-17-1
            - mongo-17-2:mongo-17-2
            - mongo-17-3:mongo-17-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-17-1
            - MONGO2=mongo-17-2
            - MONGO3=mongo-17-3
            - RS=rs17
        entrypoint: [ "/scripts/setup.sh" ]

        
