version: '2'
services:
    mongo-16-2:
        container_name: "mongo-16-2"
        image: mongobuild
        ports:
            - "30050:27017"
        command: mongod --replSet rs16 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-16-3:
        container_name: "mongo-16-3"
        image: mongobuild
        ports:
            - "30051:27017"
        command: mongod --replSet rs16 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-16-1:
        container_name: "mongo-16-1"
        image: mongobuild
        ports:
            - "30049:27017"
        command: mongod --replSet rs16 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-16-2:mongo-16-2
            - mongo-16-3:mongo-16-3
        restart: always

    mongo-rs16-setup:
        container_name: "mongo-rs16-setup"
        image: mongobuild
        depends_on:
            - "mongo-16-1"
            - "mongo-16-2"
            - "mongo-16-3"
        links:
            - mongo-16-1:mongo-16-1
            - mongo-16-2:mongo-16-2
            - mongo-16-3:mongo-16-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-16-1
            - MONGO2=mongo-16-2
            - MONGO3=mongo-16-3
            - RS=rs16
        entrypoint: [ "/scripts/setup.sh" ]

        
