version: '2'
services:
    mongo-32-2:
        container_name: "mongo-32-2"
        image: mongobuild
        ports:
            - "30098:27017"
        command: mongod --replSet rs32 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-32-3:
        container_name: "mongo-32-3"
        image: mongobuild
        ports:
            - "30099:27017"
        command: mongod --replSet rs32 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-32-1:
        container_name: "mongo-32-1"
        image: mongobuild
        ports:
            - "30097:27017"
        command: mongod --replSet rs32 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-32-2:mongo-32-2
            - mongo-32-3:mongo-32-3
        restart: always

    mongo-rs32-setup:
        container_name: "mongo-rs32-setup"
        image: mongobuild
        depends_on:
            - "mongo-32-1"
            - "mongo-32-2"
            - "mongo-32-3"
        links:
            - mongo-32-1:mongo-32-1
            - mongo-32-2:mongo-32-2
            - mongo-32-3:mongo-32-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-32-1
            - MONGO2=mongo-32-2
            - MONGO3=mongo-32-3
            - RS=rs32
        entrypoint: [ "/scripts/setup.sh" ]

        
