version: '2'
services:
    mongo-27-2:
        container_name: "mongo-27-2"
        image: mongobuild
        ports:
            - "30083:27017"
        command: mongod --replSet rs27 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-27-3:
        container_name: "mongo-27-3"
        image: mongobuild
        ports:
            - "30084:27017"
        command: mongod --replSet rs27 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-27-1:
        container_name: "mongo-27-1"
        image: mongobuild
        ports:
            - "30082:27017"
        command: mongod --replSet rs27 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-27-2:mongo-27-2
            - mongo-27-3:mongo-27-3
        restart: always

    mongo-rs27-setup:
        container_name: "mongo-rs27-setup"
        image: mongobuild
        depends_on:
            - "mongo-27-1"
            - "mongo-27-2"
            - "mongo-27-3"
        links:
            - mongo-27-1:mongo-27-1
            - mongo-27-2:mongo-27-2
            - mongo-27-3:mongo-27-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-27-1
            - MONGO2=mongo-27-2
            - MONGO3=mongo-27-3
            - RS=rs27
        entrypoint: [ "/scripts/setup.sh" ]

        
