version: '2'
services:
    mongo-41-2:
        container_name: "mongo-41-2"
        image: mongobuild
        ports:
            - "30125:27017"
        command: mongod --replSet rs41 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-41-3:
        container_name: "mongo-41-3"
        image: mongobuild
        ports:
            - "30126:27017"
        command: mongod --replSet rs41 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-41-1:
        container_name: "mongo-41-1"
        image: mongobuild
        ports:
            - "30124:27017"
        command: mongod --replSet rs41 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-41-2:mongo-41-2
            - mongo-41-3:mongo-41-3
        restart: always

    mongo-rs41-setup:
        container_name: "mongo-rs41-setup"
        image: mongobuild
        depends_on:
            - "mongo-41-1"
            - "mongo-41-2"
            - "mongo-41-3"
        links:
            - mongo-41-1:mongo-41-1
            - mongo-41-2:mongo-41-2
            - mongo-41-3:mongo-41-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-41-1
            - MONGO2=mongo-41-2
            - MONGO3=mongo-41-3
            - RS=rs41
        entrypoint: [ "/scripts/setup.sh" ]

        
