version: '2'
services:
    mongo-23-2:
        container_name: "mongo-23-2"
        image: mongobuild
        ports:
            - "30071:27017"
        command: mongod --replSet rs23 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-23-3:
        container_name: "mongo-23-3"
        image: mongobuild
        ports:
            - "30072:27017"
        command: mongod --replSet rs23 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-23-1:
        container_name: "mongo-23-1"
        image: mongobuild
        ports:
            - "30070:27017"
        command: mongod --replSet rs23 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-23-2:mongo-23-2
            - mongo-23-3:mongo-23-3
        restart: always

    mongo-rs23-setup:
        container_name: "mongo-rs23-setup"
        image: mongobuild
        depends_on:
            - "mongo-23-1"
            - "mongo-23-2"
            - "mongo-23-3"
        links:
            - mongo-23-1:mongo-23-1
            - mongo-23-2:mongo-23-2
            - mongo-23-3:mongo-23-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-23-1
            - MONGO2=mongo-23-2
            - MONGO3=mongo-23-3
            - RS=rs23
        entrypoint: [ "/scripts/setup.sh" ]

        
