version: '2'
services:
    mongo-15-2:
        container_name: "mongo-15-2"
        image: mongobuild
        ports:
            - "30047:27017"
        command: mongod --replSet rs15 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-15-3:
        container_name: "mongo-15-3"
        image: mongobuild
        ports:
            - "30048:27017"
        command: mongod --replSet rs15 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-15-1:
        container_name: "mongo-15-1"
        image: mongobuild
        ports:
            - "30046:27017"
        command: mongod --replSet rs15 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-15-2:mongo-15-2
            - mongo-15-3:mongo-15-3
        restart: always

    mongo-rs15-setup:
        container_name: "mongo-rs15-setup"
        image: mongobuild
        depends_on:
            - "mongo-15-1"
            - "mongo-15-2"
            - "mongo-15-3"
        links:
            - mongo-15-1:mongo-15-1
            - mongo-15-2:mongo-15-2
            - mongo-15-3:mongo-15-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-15-1
            - MONGO2=mongo-15-2
            - MONGO3=mongo-15-3
            - RS=rs15
        entrypoint: [ "/scripts/setup.sh" ]

        
