version: '2'
services:
    mongo-11-2:
        container_name: "mongo-11-2"
        image: mongobuild
        ports:
            - "30035:27017"
        command: mongod --replSet rs11 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-11-3:
        container_name: "mongo-11-3"
        image: mongobuild
        ports:
            - "30036:27017"
        command: mongod --replSet rs11 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-11-1:
        container_name: "mongo-11-1"
        image: mongobuild
        ports:
            - "30034:27017"
        command: mongod --replSet rs11 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-11-2:mongo-11-2
            - mongo-11-3:mongo-11-3
        restart: always

    mongo-rs11-setup:
        container_name: "mongo-rs11-setup"
        image: mongobuild
        depends_on:
            - "mongo-11-1"
            - "mongo-11-2"
            - "mongo-11-3"
        links:
            - mongo-11-1:mongo-11-1
            - mongo-11-2:mongo-11-2
            - mongo-11-3:mongo-11-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-11-1
            - MONGO2=mongo-11-2
            - MONGO3=mongo-11-3
            - RS=rs11
        entrypoint: [ "/scripts/setup.sh" ]

        
