version: '2'
services:
    mongo-34-2:
        container_name: "mongo-34-2"
        image: mongobuild
        ports:
            - "30104:27017"
        command: mongod --replSet rs34 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-34-3:
        container_name: "mongo-34-3"
        image: mongobuild
        ports:
            - "30105:27017"
        command: mongod --replSet rs34 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-34-1:
        container_name: "mongo-34-1"
        image: mongobuild
        ports:
            - "30103:27017"
        command: mongod --replSet rs34 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-34-2:mongo-34-2
            - mongo-34-3:mongo-34-3
        restart: always

    mongo-rs34-setup:
        container_name: "mongo-rs34-setup"
        image: mongobuild
        depends_on:
            - "mongo-34-1"
            - "mongo-34-2"
            - "mongo-34-3"
        links:
            - mongo-34-1:mongo-34-1
            - mongo-34-2:mongo-34-2
            - mongo-34-3:mongo-34-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-34-1
            - MONGO2=mongo-34-2
            - MONGO3=mongo-34-3
            - RS=rs34
        entrypoint: [ "/scripts/setup.sh" ]

        
