version: '2'
services:
    mongo-31-2:
        container_name: "mongo-31-2"
        image: mongobuild
        ports:
            - "30095:27017"
        command: mongod --replSet rs31 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-31-3:
        container_name: "mongo-31-3"
        image: mongobuild
        ports:
            - "30096:27017"
        command: mongod --replSet rs31 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-31-1:
        container_name: "mongo-31-1"
        image: mongobuild
        ports:
            - "30094:27017"
        command: mongod --replSet rs31 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-31-2:mongo-31-2
            - mongo-31-3:mongo-31-3
        restart: always

    mongo-rs31-setup:
        container_name: "mongo-rs31-setup"
        image: mongobuild
        depends_on:
            - "mongo-31-1"
            - "mongo-31-2"
            - "mongo-31-3"
        links:
            - mongo-31-1:mongo-31-1
            - mongo-31-2:mongo-31-2
            - mongo-31-3:mongo-31-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-31-1
            - MONGO2=mongo-31-2
            - MONGO3=mongo-31-3
            - RS=rs31
        entrypoint: [ "/scripts/setup.sh" ]

        
