version: '2'
services:
    mongo-9-2:
        container_name: "mongo-9-2"
        image: mongobuild
        ports:
            - "30029:27017"
        command: mongod --replSet rs9 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-9-3:
        container_name: "mongo-9-3"
        image: mongobuild
        ports:
            - "30030:27017"
        command: mongod --replSet rs9 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-9-1:
        container_name: "mongo-9-1"
        image: mongobuild
        ports:
            - "30028:27017"
        command: mongod --replSet rs9 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-9-2:mongo-9-2
            - mongo-9-3:mongo-9-3
        restart: always

    mongo-rs9-setup:
        container_name: "mongo-rs9-setup"
        image: mongobuild
        depends_on:
            - "mongo-9-1"
            - "mongo-9-2"
            - "mongo-9-3"
        links:
            - mongo-9-1:mongo-9-1
            - mongo-9-2:mongo-9-2
            - mongo-9-3:mongo-9-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-9-1
            - MONGO2=mongo-9-2
            - MONGO3=mongo-9-3
            - RS=rs9
        entrypoint: [ "/scripts/setup.sh" ]

        
