version: '2'
services:
    mongo-12-2:
        container_name: "mongo-12-2"
        image: mongobuild
        ports:
            - "30038:27017"
        command: mongod --replSet rs12 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-12-3:
        container_name: "mongo-12-3"
        image: mongobuild
        ports:
            - "30039:27017"
        command: mongod --replSet rs12 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-12-1:
        container_name: "mongo-12-1"
        image: mongobuild
        ports:
            - "30037:27017"
        command: mongod --replSet rs12 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-12-2:mongo-12-2
            - mongo-12-3:mongo-12-3
        restart: always

    mongo-rs12-setup:
        container_name: "mongo-rs12-setup"
        image: mongobuild
        depends_on:
            - "mongo-12-1"
            - "mongo-12-2"
            - "mongo-12-3"
        links:
            - mongo-12-1:mongo-12-1
            - mongo-12-2:mongo-12-2
            - mongo-12-3:mongo-12-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-12-1
            - MONGO2=mongo-12-2
            - MONGO3=mongo-12-3
            - RS=rs12
        entrypoint: [ "/scripts/setup.sh" ]

        
