version: '2'
services:
    mongo-21-2:
        container_name: "mongo-21-2"
        image: mongobuild
        ports:
            - "30065:27017"
        command: mongod --replSet rs21 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-21-3:
        container_name: "mongo-21-3"
        image: mongobuild
        ports:
            - "30066:27017"
        command: mongod --replSet rs21 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-21-1:
        container_name: "mongo-21-1"
        image: mongobuild
        ports:
            - "30064:27017"
        command: mongod --replSet rs21 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-21-2:mongo-21-2
            - mongo-21-3:mongo-21-3
        restart: always

    mongo-rs21-setup:
        container_name: "mongo-rs21-setup"
        image: mongobuild
        depends_on:
            - "mongo-21-1"
            - "mongo-21-2"
            - "mongo-21-3"
        links:
            - mongo-21-1:mongo-21-1
            - mongo-21-2:mongo-21-2
            - mongo-21-3:mongo-21-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-21-1
            - MONGO2=mongo-21-2
            - MONGO3=mongo-21-3
            - RS=rs21
        entrypoint: [ "/scripts/setup.sh" ]

        
