version: '2'
services:
    mongo-router:
        container_name: "mongo-router"
        image: mongobuild
        ports:
            - "30190:27017"
        depends_on:
            - "mongo-rs1-setup"
            - "mongo-rs2-setup"
            - mongo-rs3-setup
            - mongo-rs4-setup
            - mongo-rs5-setup
            - mongo-rs6-setup
            - mongo-rs7-setup
            - mongo-rs8-setup
            - mongo-rs9-setup
            - mongo-rs10-setup
            - mongo-rs11-setup
            - mongo-rs12-setup
            - mongo-rs13-setup
            - mongo-rs14-setup
            - mongo-rs15-setup
            - mongo-rs16-setup
            - mongo-rs17-setup
            - mongo-rs18-setup
            - mongo-rs19-setup
            - mongo-rs20-setup
            - mongo-rs21-setup
            - mongo-rs22-setup
            - mongo-rs23-setup
            - mongo-rs24-setup
            - mongo-rs25-setup
            - mongo-rs26-setup
            - mongo-rs27-setup
            - mongo-rs28-setup
            - mongo-rs29-setup
            - mongo-rs30-setup
            - mongo-rs31-setup
            - mongo-rs32-setup
            - mongo-rs33-setup
            - mongo-rs34-setup
            - mongo-rs35-setup
            - mongo-rs36-setup
            - mongo-rs37-setup
            - mongo-rs38-setup
            - mongo-rs39-setup
            - mongo-rs40-setup
            - mongo-rs41-setup
            - "mongo-cnf-setup"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
            - mongo-3-1:mongo-3-1
            - mongo-3-2:mongo-3-2
            - mongo-3-3:mongo-3-3
            - mongo-4-1:mongo-4-1
            - mongo-4-2:mongo-4-2
            - mongo-4-3:mongo-4-3
            - mongo-5-1:mongo-5-1
            - mongo-5-2:mongo-5-2
            - mongo-5-3:mongo-5-3
            - mongo-6-1:mongo-6-1
            - mongo-6-2:mongo-6-2
            - mongo-6-3:mongo-6-3
            - mongo-7-1:mongo-7-1
            - mongo-7-2:mongo-7-2
            - mongo-7-3:mongo-7-3
            - mongo-8-1:mongo-8-1
            - mongo-8-2:mongo-8-2
            - mongo-8-3:mongo-8-3
            - mongo-9-1:mongo-9-1
            - mongo-9-2:mongo-9-2
            - mongo-9-3:mongo-9-3
            - mongo-10-1:mongo-10-1
            - mongo-10-2:mongo-10-2
            - mongo-10-3:mongo-10-3
            - mongo-11-1:mongo-11-1
            - mongo-11-2:mongo-11-2
            - mongo-11-3:mongo-11-3
            - mongo-12-1:mongo-12-1
            - mongo-12-2:mongo-12-2
            - mongo-12-3:mongo-12-3
            - mongo-13-1:mongo-13-1
            - mongo-13-2:mongo-13-2
            - mongo-13-3:mongo-13-3
            - mongo-14-1:mongo-14-1
            - mongo-14-2:mongo-14-2
            - mongo-14-3:mongo-14-3
            - mongo-15-1:mongo-15-1
            - mongo-15-2:mongo-15-2
            - mongo-15-3:mongo-15-3
            - mongo-16-1:mongo-16-1
            - mongo-16-2:mongo-16-2
            - mongo-16-3:mongo-16-3
            - mongo-17-1:mongo-17-1
            - mongo-17-2:mongo-17-2
            - mongo-17-3:mongo-17-3
            - mongo-18-1:mongo-18-1
            - mongo-18-2:mongo-18-2
            - mongo-18-3:mongo-18-3
            - mongo-19-1:mongo-19-1
            - mongo-19-2:mongo-19-2
            - mongo-19-3:mongo-19-3
            - mongo-20-1:mongo-20-1
            - mongo-20-2:mongo-20-2
            - mongo-20-3:mongo-20-3
            - mongo-21-1:mongo-21-1
            - mongo-21-2:mongo-21-2
            - mongo-21-3:mongo-21-3
            - mongo-22-1:mongo-22-1
            - mongo-22-2:mongo-22-2
            - mongo-22-3:mongo-22-3
            - mongo-23-1:mongo-23-1
            - mongo-23-2:mongo-23-2
            - mongo-23-3:mongo-23-3
            - mongo-24-1:mongo-24-1
            - mongo-24-2:mongo-24-2
            - mongo-24-3:mongo-24-3
            - mongo-25-1:mongo-25-1
            - mongo-25-2:mongo-25-2
            - mongo-25-3:mongo-25-3
            - mongo-26-1:mongo-26-1
            - mongo-26-2:mongo-26-2
            - mongo-26-3:mongo-26-3
            - mongo-27-1:mongo-27-1
            - mongo-27-2:mongo-27-2
            - mongo-27-3:mongo-27-3
            - mongo-28-1:mongo-28-1
            - mongo-28-2:mongo-28-2
            - mongo-28-3:mongo-28-3
            - mongo-29-1:mongo-29-1
            - mongo-29-2:mongo-29-2
            - mongo-29-3:mongo-29-3
            - mongo-30-1:mongo-30-1
            - mongo-30-2:mongo-30-2
            - mongo-30-3:mongo-30-3
            - mongo-31-1:mongo-31-1
            - mongo-31-2:mongo-31-2
            - mongo-31-3:mongo-31-3
            - mongo-32-1:mongo-32-1
            - mongo-32-2:mongo-32-2
            - mongo-32-3:mongo-32-3
            - mongo-33-1:mongo-33-1
            - mongo-33-2:mongo-33-2
            - mongo-33-3:mongo-33-3
            - mongo-34-1:mongo-34-1
            - mongo-34-2:mongo-34-2
            - mongo-34-3:mongo-34-3
            - mongo-35-1:mongo-35-1
            - mongo-35-2:mongo-35-2
            - mongo-35-3:mongo-35-3
            - mongo-36-1:mongo-36-1
            - mongo-36-2:mongo-36-2
            - mongo-36-3:mongo-36-3
            - mongo-37-1:mongo-37-1
            - mongo-37-2:mongo-37-2
            - mongo-37-3:mongo-37-3
            - mongo-38-1:mongo-38-1
            - mongo-38-2:mongo-38-2
            - mongo-38-3:mongo-38-3
            - mongo-39-1:mongo-39-1
            - mongo-39-2:mongo-39-2
            - mongo-39-3:mongo-39-3
            - mongo-40-1:mongo-40-1
            - mongo-40-2:mongo-40-2
            - mongo-40-3:mongo-40-3
            - mongo-41-1:mongo-41-1
            - mongo-41-2:mongo-41-2
            - mongo-41-3:mongo-41-3
        command: mongos --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017
        restart: "no"

    mongo-shard-setup:
        container_name: "mongo-shard-setup"
        image: mongobuild
        depends_on:
            - "mongo-router"
        links:
            - mongo-router:mongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=mongo-router
            - MONGO11=mongo-1-1
            - MONGO12=mongo-1-2
            - MONGO13=mongo-1-3
            - MONGO21=mongo-2-1
            - MONGO22=mongo-2-2
            - MONGO23=mongo-2-3
            - MONGO31=mongo-3-1
            - MONGO32=mongo-3-2
            - MONGO33=mongo-3-3
            - MONGO41=mongo-4-1
            - MONGO42=mongo-4-2
            - MONGO43=mongo-4-3
            - MONGO51=mongo-5-1
            - MONGO52=mongo-5-2
            - MONGO53=mongo-5-3
            - MONGO61=mongo-6-1
            - MONGO62=mongo-6-2
            - MONGO63=mongo-6-3
            - MONGO71=mongo-7-1
            - MONGO72=mongo-7-2
            - MONGO73=mongo-7-3
            - MONGO81=mongo-8-1
            - MONGO82=mongo-8-2
            - MONGO83=mongo-8-3
            - MONGO91=mongo-9-1
            - MONGO92=mongo-9-2
            - MONGO93=mongo-9-3
            - MONGO101=mongo-10-1
            - MONGO102=mongo-10-2
            - MONGO103=mongo-10-3
            - MONGO111=mongo-11-1
            - MONGO112=mongo-11-2
            - MONGO113=mongo-11-3
            - MONGO121=mongo-12-1
            - MONGO122=mongo-12-2
            - MONGO123=mongo-12-3
            - MONGO131=mongo-13-1
            - MONGO132=mongo-13-2
            - MONGO133=mongo-13-3
            - MONGO141=mongo-14-1
            - MONGO142=mongo-14-2
            - MONGO143=mongo-14-3
            - MONGO151=mongo-15-1
            - MONGO152=mongo-15-2
            - MONGO153=mongo-15-3
            - MONGO161=mongo-16-1
            - MONGO162=mongo-16-2
            - MONGO163=mongo-16-3
            - MONGO171=mongo-17-1
            - MONGO172=mongo-17-2
            - MONGO173=mongo-17-3
            - MONGO181=mongo-18-1
            - MONGO182=mongo-18-2
            - MONGO183=mongo-18-3
            - MONGO191=mongo-19-1
            - MONGO192=mongo-19-2
            - MONGO193=mongo-19-3
            - MONGO201=mongo-20-1
            - MONGO202=mongo-20-2
            - MONGO203=mongo-20-3
            - MONGO211=mongo-21-1
            - MONGO212=mongo-21-2
            - MONGO213=mongo-21-3
            - MONGO221=mongo-22-1
            - MONGO222=mongo-22-2
            - MONGO223=mongo-22-3
            - MONGO231=mongo-23-1
            - MONGO232=mongo-23-2
            - MONGO233=mongo-23-3
            - MONGO241=mongo-24-1
            - MONGO242=mongo-24-2
            - MONGO243=mongo-24-3
            - MONGO251=mongo-25-1
            - MONGO252=mongo-25-2
            - MONGO253=mongo-25-3
            - MONGO261=mongo-26-1
            - MONGO262=mongo-26-2
            - MONGO263=mongo-26-3
            - MONGO271=mongo-27-1
            - MONGO272=mongo-27-2
            - MONGO273=mongo-27-3
            - MONGO281=mongo-28-1
            - MONGO282=mongo-28-2
            - MONGO283=mongo-28-3
            - MONGO291=mongo-29-1
            - MONGO292=mongo-29-2
            - MONGO293=mongo-29-3
            - MONGO301=mongo-30-1
            - MONGO302=mongo-30-2
            - MONGO303=mongo-30-3
            - MONGO311=mongo-31-1
            - MONGO312=mongo-31-2
            - MONGO313=mongo-31-3
            - MONGO321=mongo-32-1
            - MONGO322=mongo-32-2
            - MONGO323=mongo-32-3
            - MONGO331=mongo-33-1
            - MONGO332=mongo-33-2
            - MONGO333=mongo-33-3
            - MONGO341=mongo-34-1
            - MONGO342=mongo-34-2
            - MONGO343=mongo-34-3
            - MONGO351=mongo-35-1
            - MONGO352=mongo-35-2
            - MONGO353=mongo-35-3
            - MONGO361=mongo-36-1
            - MONGO362=mongo-36-2
            - MONGO363=mongo-36-3
            - MONGO371=mongo-37-1
            - MONGO372=mongo-37-2
            - MONGO373=mongo-37-3
            - MONGO381=mongo-38-1
            - MONGO382=mongo-38-2
            - MONGO383=mongo-38-3
            - MONGO391=mongo-39-1
            - MONGO392=mongo-39-2
            - MONGO393=mongo-39-3
            - MONGO401=mongo-40-1
            - MONGO402=mongo-40-2
            - MONGO403=mongo-40-3
            - MONGO411=mongo-41-1
            - MONGO412=mongo-41-2
            - MONGO413=mongo-41-3
            - RS1=rs1
            - RS2=rs2
            - RS3=rs3
            - RS4=rs4
            - RS5=rs5
            - RS6=rs6
            - RS7=rs7
            - RS8=rs8
            - RS9=rs9
            - RS10=rs10
            - RS11=rs11
            - RS12=rs12
            - RS13=rs13
            - RS14=rs14
            - RS15=rs15
            - RS16=rs16
            - RS17=rs17
            - RS18=rs18
            - RS19=rs19
            - RS20=rs20
            - RS21=rs21
            - RS22=rs22
            - RS23=rs23
            - RS24=rs24
            - RS25=rs25
            - RS26=rs26
            - RS27=rs27
            - RS28=rs28
            - RS29=rs29
            - RS30=rs30
            - RS31=rs31
            - RS32=rs32
            - RS33=rs33
            - RS34=rs34
            - RS35=rs35
            - RS36=rs36
            - RS37=rs37
            - RS38=rs38
            - RS39=rs39
            - RS40=rs40
            - RS41=rs41
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init-shard-41.sh" ]
        restart: on-failure:20
