version: '2'
services:
    mongo-20-2:
        container_name: "mongo-20-2"
        image: mongobuild
        ports:
            - "30062:27017"
        command: mongod --replSet rs20 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-20-3:
        container_name: "mongo-20-3"
        image: mongobuild
        ports:
            - "30063:27017"
        command: mongod --replSet rs20 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-20-1:
        container_name: "mongo-20-1"
        image: mongobuild
        ports:
            - "30061:27017"
        command: mongod --replSet rs20 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-20-2:mongo-20-2
            - mongo-20-3:mongo-20-3
        restart: always

    mongo-rs20-setup:
        container_name: "mongo-rs20-setup"
        image: mongobuild
        depends_on:
            - "mongo-20-1"
            - "mongo-20-2"
            - "mongo-20-3"
        links:
            - mongo-20-1:mongo-20-1
            - mongo-20-2:mongo-20-2
            - mongo-20-3:mongo-20-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-20-1
            - MONGO2=mongo-20-2
            - MONGO3=mongo-20-3
            - RS=rs20
        entrypoint: [ "/scripts/setup.sh" ]

        
