version: '2'
services:
    mongo-7-2:
        container_name: "mongo-7-2"
        image: mongobuild
        ports:
            - "30023:27017"
        command: mongod --replSet rs7 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-7-3:
        container_name: "mongo-7-3"
        image: mongobuild
        ports:
            - "30024:27017"
        command: mongod --replSet rs7 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-7-1:
        container_name: "mongo-7-1"
        image: mongobuild
        ports:
            - "30022:27017"
        command: mongod --replSet rs7 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-7-2:mongo-7-2
            - mongo-7-3:mongo-7-3
        restart: always

    mongo-rs7-setup:
        container_name: "mongo-rs7-setup"
        image: mongobuild
        depends_on:
            - "mongo-7-1"
            - "mongo-7-2"
            - "mongo-7-3"
        links:
            - mongo-7-1:mongo-7-1
            - mongo-7-2:mongo-7-2
            - mongo-7-3:mongo-7-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-7-1
            - MONGO2=mongo-7-2
            - MONGO3=mongo-7-3
            - RS=rs7
        entrypoint: [ "/scripts/setup.sh" ]

        
