version: '2'
services:
    mongo-44-2:
        container_name: "mongo-44-2"
        image: mongobuild
        ports:
            - "30134:27017"
        command: mongod --replSet rs44 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-44-3:
        container_name: "mongo-44-3"
        image: mongobuild
        ports:
            - "30135:27017"
        command: mongod --replSet rs44 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-44-1:
        container_name: "mongo-44-1"
        image: mongobuild
        ports:
            - "30133:27017"
        command: mongod --replSet rs44 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-44-2:mongo-44-2
            - mongo-44-3:mongo-44-3
        restart: always

    mongo-rs44-setup:
        container_name: "mongo-rs44-setup"
        image: mongobuild
        depends_on:
            - "mongo-44-1"
            - "mongo-44-2"
            - "mongo-44-3"
        links:
            - mongo-44-1:mongo-44-1
            - mongo-44-2:mongo-44-2
            - mongo-44-3:mongo-44-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-44-1
            - MONGO2=mongo-44-2
            - MONGO3=mongo-44-3
            - RS=rs44
        entrypoint: [ "/scripts/setup.sh" ]

        
