version: '2'
services:
    mongo-5-2:
        container_name: "mongo-5-2"
        image: mongobuild
        ports:
            - "30017:27017"
        command: mongod --replSet rs5 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-5-3:
        container_name: "mongo-5-3"
        image: mongobuild
        ports:
            - "30018:27017"
        command: mongod --replSet rs5 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-5-1:
        container_name: "mongo-5-1"
        image: mongobuild
        ports:
            - "30016:27017"
        command: mongod --replSet rs5 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-5-2:mongo-5-2
            - mongo-5-3:mongo-5-3
        restart: always

    mongo-rs5-setup:
        container_name: "mongo-rs5-setup"
        image: mongobuild
        depends_on:
            - "mongo-5-1"
            - "mongo-5-2"
            - "mongo-5-3"
        links:
            - mongo-5-1:mongo-5-1
            - mongo-5-2:mongo-5-2
            - mongo-5-3:mongo-5-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-5-1
            - MONGO2=mongo-5-2
            - MONGO3=mongo-5-3
            - RS=rs5
        entrypoint: [ "/scripts/setup.sh" ]

        
