version: '2'
services:
    mongo-42-2:
        container_name: "mongo-42-2"
        image: mongobuild
        ports:
            - "300128:27017"
        command: mongod --replSet rs42 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-42-3:
        container_name: "mongo-42-3"
        image: mongobuild
        ports:
            - "300129:27017"
        command: mongod --replSet rs42 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-42-1:
        container_name: "mongo-42-1"
        image: mongobuild
        ports:
            - "300127:27017"
        command: mongod --replSet rs42 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-42-2:mongo-42-2
            - mongo-42-3:mongo-42-3
        restart: always

    mongo-rs42-setup:
        container_name: "mongo-rs42-setup"
        image: mongobuild
        depends_on:
            - "mongo-42-1"
            - "mongo-42-2"
            - "mongo-42-3"
        links:
            - mongo-42-1:mongo-42-1
            - mongo-42-2:mongo-42-2
            - mongo-42-3:mongo-42-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-42-1
            - MONGO2=mongo-42-2
            - MONGO3=mongo-42-3
            - RS=rs42
        entrypoint: [ "/scripts/setup.sh" ]

        
