version: '2'
services:
    mongo-48-2:
        container_name: "mongo-48-2"
        image: mongobuild
        ports:
            - "30146:27017"
        command: mongod --replSet rs48 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-48-3:
        container_name: "mongo-48-3"
        image: mongobuild
        ports:
            - "30147:27017"
        command: mongod --replSet rs48 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-48-1:
        container_name: "mongo-48-1"
        image: mongobuild
        ports:
            - "30145:27017"
        command: mongod --replSet rs48 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-48-2:mongo-48-2
            - mongo-48-3:mongo-48-3
        restart: always

    mongo-rs48-setup:
        container_name: "mongo-rs48-setup"
        image: mongobuild
        depends_on:
            - "mongo-48-1"
            - "mongo-48-2"
            - "mongo-48-3"
        links:
            - mongo-48-1:mongo-48-1
            - mongo-48-2:mongo-48-2
            - mongo-48-3:mongo-48-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-48-1
            - MONGO2=mongo-48-2
            - MONGO3=mongo-48-3
            - RS=rs48
        entrypoint: [ "/scripts/setup.sh" ]

        
