version: '2'
services:
    mongo-45-2:
        container_name: "mongo-45-2"
        image: mongobuild
        ports:
            - "30137:27017"
        command: mongod --replSet rs45 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-45-3:
        container_name: "mongo-45-3"
        image: mongobuild
        ports:
            - "30138:27017"
        command: mongod --replSet rs45 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-45-1:
        container_name: "mongo-45-1"
        image: mongobuild
        ports:
            - "30136:27017"
        command: mongod --replSet rs45 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-45-2:mongo-45-2
            - mongo-45-3:mongo-45-3
        restart: always

    mongo-rs45-setup:
        container_name: "mongo-rs45-setup"
        image: mongobuild
        depends_on:
            - "mongo-45-1"
            - "mongo-45-2"
            - "mongo-45-3"
        links:
            - mongo-45-1:mongo-45-1
            - mongo-45-2:mongo-45-2
            - mongo-45-3:mongo-45-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-45-1
            - MONGO2=mongo-45-2
            - MONGO3=mongo-45-3
            - RS=rs45
        entrypoint: [ "/scripts/setup.sh" ]

        
