version: '2'
services:
    mongo-14-2:
        container_name: "mongo-14-2"
        image: mongobuild
        ports:
            - "30044:27017"
        command: mongod --replSet rs14 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-14-3:
        container_name: "mongo-14-3"
        image: mongobuild
        ports:
            - "30045:27017"
        command: mongod --replSet rs14 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-14-1:
        container_name: "mongo-14-1"
        image: mongobuild
        ports:
            - "30043:27017"
        command: mongod --replSet rs14 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-14-2:mongo-14-2
            - mongo-14-3:mongo-14-3
        restart: always

    mongo-rs14-setup:
        container_name: "mongo-rs14-setup"
        image: mongobuild
        depends_on:
            - "mongo-14-1"
            - "mongo-14-2"
            - "mongo-14-3"
        links:
            - mongo-14-1:mongo-14-1
            - mongo-14-2:mongo-14-2
            - mongo-14-3:mongo-14-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-14-1
            - MONGO2=mongo-14-2
            - MONGO3=mongo-14-3
            - RS=rs14
        entrypoint: [ "/scripts/setup.sh" ]

        
